### ISSUE TITLE
Setting up PurgeCSS with tailwindcss-transitions

### ISSUE THREAD

**Issue by leobauza** [benface/tailwindcss-transitions#9]
Hey, 

Awesome plugin...I am having trouble figuring out the best way to configure purgeCSS to not delete this:

```css
/* base styles for the default transition duration, timing function, and delay (when they differ from the CSS defaults) */
*, *::before, *::after {
  --transition-duration: 250ms;
  /* when the default timing function is a value other than "ease": */
  --transition-timing-function: [default-timing-function];
  /* when the default delay is a value other than zero: */
  --transition-delay: [default-delay];
}
```

I have the standard configuration for tailwind with purgeCSS and I can't think of exactly how to whitelist this specific part I guess I could fork and wrap that in a `purgeCSS` ignore but maybe that should be the default? Or maybe you can think of a way to whitelist that part of it.

Cheers!
